name: AstroOps CI/CD

on:
  schedule:
    - cron: '*/10 * * * *'  # every 10 minutes
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests

      - name: Check Solar Flare Activity
        id: flare_check
        env:
          NASA_API_KEY: ${{ secrets.NASA_API_KEY }}
        run: python AstroOps-NASA/solar-flare-checker.py

      - name: Conditional Deployment
        if: steps.flare_check.outcome == 'success'
        run: echo "✅ Safe to deploy — Launching AstroOps pipeline!"

      - name: Send Email Notification
        if: always()
        env:
          GMAIL_USER: ${{ secrets.GMAIL_USER }}
          GMAIL_PASSWORD: ${{ secrets.GMAIL_PASSWORD }}
        run: |
          python3 <<EOF
          import smtplib
          from email.mime.text import MIMEText
          from email.mime.multipart import MIMEMultipart
          import os

          status = "${{ steps.flare_check.outcome }}"
          subject = "AstroOps Pipeline Status"
          body = "✅ Deployment was successful!"

          if status != "success":
              subject = "AstroOps Pipeline Failure"
              body = "⚠️ Solar flare detected, deployment aborted."

          sender = os.environ["GMAIL_USER"]
          password = os.environ["GMAIL_PASSWORD"]
          recipient = "your_email@example.com"  # <-- Replace this

          msg = MIMEMultipart()
          msg["From"] = sender
          msg["To"] = recipient
          msg["Subject"] = subject
          msg.attach(MIMEText(body, "plain"))

          with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
              server.login(sender, password)
              server.send_message(msg)
          EOF

