name: AstroOps CI/CD

on:
  schedule:
    - cron: '*/10 * * * *'  # every 10 mins
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests

      - name: Check Solar Flare Activity
        id: flare_check
        env:
          NASA_API_KEY: ${{ secrets.NASA_API_KEY }}
        run: python AstroOps-NASA/solar-flare-checker.py

      - name: Conditional Deployment
        if: steps.flare_check.outcome == 'success'
        run: echo "✅ Safe to deploy — Launching AstroOps pipeline!"

      - name: Send Email Notification
        if: always()  # Runs after all steps, even if the previous steps fail or succeed
        run: |
          SUBJECT="AstroOps Pipeline Status"
          MESSAGE="Deployment was successful!"
          
          if [ "${{ steps.flare_check.outcome }}" != "success" ]; then
            SUBJECT="AstroOps Pipeline Failure"
            MESSAGE="Solar flare detected, deployment aborted."
          fi
          
          echo -e "Subject:${SUBJECT}\n\n${MESSAGE}" | sendmail -v -S smtp.gmail.com:587 -f "${{ secrets.GMAIL_USER }}" -au"${{ secrets.GMAIL_USER }}" -ap"${{ secrets.GMAIL_PASSWORD }}" recipient@example.com
